name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node 12
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
  test-e2e:
    runs-on: ubuntu-latest
    name: E2E
    strategy:
      matrix:
        disableCustomResourceManager: ['true', 'false']
        helmVersion: ['V2', 'V3']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: azure/setup-helm@v1
        with:
          version: 2.16.1
        if: matrix.helmVersion == 'V2'
      - run: npm install
      - run: |
          helm version
          npm run test-e2e -- ${{ matrix.disableCustomResourceManager }} ${{ matrix.helmVersion }}
